INSERT INTO HABITACION (CODIGO, PLANTA, NUMERO, TIPO, PRECIO, DESCUENTO_EMPLEADO, CODIGO_RESERVA)
VALUES (12345, 1, 11, 'Básica', 30, 10, 0);

INSERT INTO HABITACION (CODIGO, PLANTA, NUMERO, TIPO, PRECIO, DESCUENTO_EMPLEADO, CODIGO_RESERVA)
VALUES (12346, 1, 12, 'Doble', 50, 10, 0);

INSERT INTO HABITACION (CODIGO, PLANTA, NUMERO, TIPO, PRECIO, DESCUENTO_EMPLEADO, CODIGO_RESERVA)
VALUES (12347, 1, 13, 'Suite', 70, 10, 0);