CREATE TABLE `HABITACION` (
`CODIGO` int NOT NULL,
`PLANTA` int DEFAULT NULL,
`NUMERO` int DEFAULT NULL,
`TIPO` varchar(45) DEFAULT NULL,
`PRECIO` int DEFAULT NULL,
`DESCUENTO_EMPLEADO` int DEFAULT NULL,
`CODIGO_RESERVA` int DEFAULT NULL,
PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci